import { createFileRoute } from '@tanstack/react-router'
import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { lectureService } from '@/services/lectureService'
import { aiOutputService } from '@/services/aiOutputService'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Send, BrainCircuit, BotMessageSquare } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/lectures/$id')({
  component: LectureDetailsPage,
})

function LectureDetailsPage() {
  const { id } = Route.useParams()
  const lectureId = Number(id)
  
  const [query, setQuery] = useState('')
  const [qaResult, setQaResult] = useState<{answer: string, results: any[], found: boolean} | null>(null)
  const [queryLoading, setQueryLoading] = useState(false)

  const { data: lecture } = useQuery({
    queryKey: ['lecture', lectureId],
    queryFn: () => lectureService.getById(lectureId),
    refetchInterval: (query) => {
        const data = query.state.data as any
        return data?.processingStatus === 'COMPLETED' || data?.processingStatus === 'FAILED' ? false : 3000
    },
  })

  const { data: aiOutputs } = useQuery({
    queryKey: ['ai-outputs', lectureId],
    queryFn: () => aiOutputService.getAll(lectureId),
    enabled: lecture?.processingStatus === 'COMPLETED',
  })

  const handleQuery = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!query.trim()) return
    setQueryLoading(true)
    try {
      const res = await aiOutputService.queryDocMind(lectureId, query)
      console.log("raw response:", res)
      setQaResult({
        answer: res.synthesised_answer,
        results: res.results,
        found: res.found
      })
    } catch (error) {
      console.error(error)
    } finally {
      setQueryLoading(false)
    }
  }

  if (lecture?.processingStatus !== 'COMPLETED') {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] space-y-4">
        <BrainCircuit className="h-16 w-16 text-primary animate-pulse" />
        <h2 className="text-2xl font-bold tracking-tight">DocMind AI is Processing...</h2>
        <p className="text-muted-foreground">Extracting insights, generating summaries, and creating revision sheets.</p>
        <p className="text-xs mt-4 text-primary/70">This page will automatically refresh.</p>
      </div>
    )
  }

  const getOutput = (type: string) => aiOutputs?.find((o) => o.outputType === type)?.outputContent || 'No data generated.'

  return (
    <div className="space-y-8 max-w-5xl mx-auto pb-12">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Analysis</h1>
          <div className="text-muted-foreground mt-1 flex items-center gap-2 text-sm">
            Generated by DocMind Engine <Badge className="bg-indigo-500/20 text-indigo-400 hover:bg-indigo-500/30">Processed</Badge>
          </div>
        </div>
      </div>

      <Tabs defaultValue="summary" className="w-full">
        <TabsList className="grid w-full grid-cols-4 bg-card border border-border">
          <TabsTrigger value="summary">Summary</TabsTrigger>
          <TabsTrigger value="keywords">Keywords</TabsTrigger>
          <TabsTrigger value="revision">Revision Sheet</TabsTrigger>
          <TabsTrigger value="important">Important Points</TabsTrigger>
        </TabsList>
        
        <div className="mt-6 border-l-4 border-indigo-500 pl-6 py-2">
          <TabsContent value="summary">
            <Card className="bg-card border-none shadow-none">
              <CardHeader className="px-0 pt-0">
                <CardTitle className="text-xl text-primary">Executive Summary</CardTitle>
              </CardHeader>
              <CardContent className="px-0 whitespace-pre-wrap text-muted-foreground leading-relaxed">
                {getOutput('SUMMARY')}
              </CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="keywords">
            <Card className="bg-card border-none shadow-none">
              <CardHeader className="px-0 pt-0">
                <CardTitle className="text-xl text-primary">Key Topics</CardTitle>
              </CardHeader>
              <CardContent className="px-0 flex flex-wrap gap-2">
                {getOutput('KEYWORDS').split(',').map((kw: string, i: number) => (
                  kw.trim() && <Badge key={i} variant="secondary" className="px-3 py-1 text-sm bg-accent">{kw.trim()}</Badge>
                ))}
              </CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="revision">
            <Card className="bg-card border-none shadow-none">
              <CardHeader className="px-0 pt-0">
                <CardTitle className="text-xl text-primary">Structured Revision Sheet</CardTitle>
              </CardHeader>
              <CardContent className="px-0 whitespace-pre-wrap text-muted-foreground leading-relaxed font-mono text-sm bg-slate-900 p-6 rounded-md">
                {getOutput('REVISION_SHEET')}
              </CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="important">
             <Card className="bg-card border-none shadow-none">
              <CardHeader className="px-0 pt-0">
                <CardTitle className="text-xl text-primary">Crucial Points to Remember</CardTitle>
              </CardHeader>
              <CardContent className="px-0 whitespace-pre-wrap text-muted-foreground leading-relaxed">
                {getOutput('IMPORTANT_POINTS')}
              </CardContent>
            </Card>
          </TabsContent>
        </div>
      </Tabs>

      <Card className="border border-indigo-500/30 shadow-lg shadow-indigo-500/5 bg-slate-950/50">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BotMessageSquare className="h-5 w-5 text-indigo-400" />
            Ask DocMind
          </CardTitle>
          <CardDescription>Ask a question about this lecture. The ML engine will find the most relevant chunks.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <form onSubmit={handleQuery} className="flex gap-3">
            <Input 
              value={query} 
              onChange={(e) => setQuery(e.target.value)} 
              placeholder="e.g. What is the main cause of..." 
              className="flex-1 bg-background"
            />
            <Button type="submit" disabled={queryLoading || !query.trim()} className="bg-indigo-600 hover:bg-indigo-700">
              {queryLoading ? 'Thinking...' : <><Send className="mr-2 h-4 w-4" /> Ask AI</>}
            </Button>
          </form>

          {qaResult && (
            <div className="space-y-4 pt-4 border-t border-border">

              <Card className={`p-4 ${qaResult.found ? 'border-indigo-500/30 bg-indigo-500/5' : 'border-yellow-500/30 bg-yellow-500/5'}`}>
                <p className="text-sm font-medium mb-1 text-muted-foreground">Answer</p>
                <p className="text-sm text-foreground/90 leading-relaxed">{qaResult.answer}</p>
              </Card>

              {qaResult.found && qaResult.results?.length > 0 && (
                <>
                  <h3 className="font-semibold text-sm text-muted-foreground uppercase tracking-wider">Top Results</h3>
                  {qaResult.results.map((res: any, idx: number) => (
                    <div key={idx} className="p-4 rounded-lg bg-card border border-border">
                      <div className="flex justify-between items-start mb-2">
                        <Badge variant="outline" className="text-indigo-400 border-indigo-500/30">Match Score: {res.score?.toFixed(2)}</Badge>
                      </div>
                      <p className="text-sm text-foreground/90 leading-relaxed">{res.text}</p>
                    </div>
                  ))}
                </>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
