export const ENUMS = {
  SUBJECT_TAG: ["EXAM", "PRACTICE", "REVISION"],
  DEADLINE_TYPE: ["EXAM", "ASSIGNMENT", "TARGET"],
  STUDY_STATUS: ["PLANNED", "COMPLETED", "MISSED"],
  REVISION_STATUS: ["COMPLETED", "PENDING", "MISSED"],
};